//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OUT_DOOR_ANDROID.Sync_ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncSoap", Namespace="http://tempuri.org/")]
    public partial class Sync : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback carreOperationCompleted;
        
        private System.Threading.SendOrPostCallback helloOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyWbOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServerDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDataBaseDefinitionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTableDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sync() {
            this.Url = "http://37.187.168.96/TRC_Chauffeur_dev/Sync.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event carreCompletedEventHandler carreCompleted;
        
        /// <remarks/>
        public event helloCompletedEventHandler helloCompleted;
        
        /// <remarks/>
        public event VerifyWbCompletedEventHandler VerifyWbCompleted;
        
        /// <remarks/>
        public event getServerDateCompletedEventHandler getServerDateCompleted;
        
        /// <remarks/>
        public event getDataBaseDefinitionsCompletedEventHandler getDataBaseDefinitionsCompleted;
        
        /// <remarks/>
        public event setUpdateCompletedEventHandler setUpdateCompleted;
        
        /// <remarks/>
        public event getTableDataCompletedEventHandler getTableDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/carre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int carre(int a) {
            object[] results = this.Invoke("carre", new object[] {
                        a});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void carreAsync(int a) {
            this.carreAsync(a, null);
        }
        
        /// <remarks/>
        public void carreAsync(int a, object userState) {
            if ((this.carreOperationCompleted == null)) {
                this.carreOperationCompleted = new System.Threading.SendOrPostCallback(this.OncarreOperationCompleted);
            }
            this.InvokeAsync("carre", new object[] {
                        a}, this.carreOperationCompleted, userState);
        }
        
        private void OncarreOperationCompleted(object arg) {
            if ((this.carreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.carreCompleted(this, new carreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/hello", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string hello() {
            object[] results = this.Invoke("hello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void helloAsync() {
            this.helloAsync(null);
        }
        
        /// <remarks/>
        public void helloAsync(object userState) {
            if ((this.helloOperationCompleted == null)) {
                this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
            }
            this.InvokeAsync("hello", new object[0], this.helloOperationCompleted, userState);
        }
        
        private void OnhelloOperationCompleted(object arg) {
            if ((this.helloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyWb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerifyWb(string RessourceID, string deviceID, string IP) {
            object[] results = this.Invoke("VerifyWb", new object[] {
                        RessourceID,
                        deviceID,
                        IP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyWbAsync(string RessourceID, string deviceID, string IP) {
            this.VerifyWbAsync(RessourceID, deviceID, IP, null);
        }
        
        /// <remarks/>
        public void VerifyWbAsync(string RessourceID, string deviceID, string IP, object userState) {
            if ((this.VerifyWbOperationCompleted == null)) {
                this.VerifyWbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyWbOperationCompleted);
            }
            this.InvokeAsync("VerifyWb", new object[] {
                        RessourceID,
                        deviceID,
                        IP}, this.VerifyWbOperationCompleted, userState);
        }
        
        private void OnVerifyWbOperationCompleted(object arg) {
            if ((this.VerifyWbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyWbCompleted(this, new VerifyWbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getServerDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getServerDate() {
            object[] results = this.Invoke("getServerDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getServerDateAsync() {
            this.getServerDateAsync(null);
        }
        
        /// <remarks/>
        public void getServerDateAsync(object userState) {
            if ((this.getServerDateOperationCompleted == null)) {
                this.getServerDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServerDateOperationCompleted);
            }
            this.InvokeAsync("getServerDate", new object[0], this.getServerDateOperationCompleted, userState);
        }
        
        private void OngetServerDateOperationCompleted(object arg) {
            if ((this.getServerDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServerDateCompleted(this, new getServerDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDataBaseDefinitions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDataBaseDefinitions(string appName) {
            object[] results = this.Invoke("getDataBaseDefinitions", new object[] {
                        appName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDataBaseDefinitionsAsync(string appName) {
            this.getDataBaseDefinitionsAsync(appName, null);
        }
        
        /// <remarks/>
        public void getDataBaseDefinitionsAsync(string appName, object userState) {
            if ((this.getDataBaseDefinitionsOperationCompleted == null)) {
                this.getDataBaseDefinitionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataBaseDefinitionsOperationCompleted);
            }
            this.InvokeAsync("getDataBaseDefinitions", new object[] {
                        appName}, this.getDataBaseDefinitionsOperationCompleted, userState);
        }
        
        private void OngetDataBaseDefinitionsOperationCompleted(object arg) {
            if ((this.getDataBaseDefinitionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataBaseDefinitionsCompleted(this, new getDataBaseDefinitionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setUpdate(string appName, string name, string param) {
            object[] results = this.Invoke("setUpdate", new object[] {
                        appName,
                        name,
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setUpdateAsync(string appName, string name, string param) {
            this.setUpdateAsync(appName, name, param, null);
        }
        
        /// <remarks/>
        public void setUpdateAsync(string appName, string name, string param, object userState) {
            if ((this.setUpdateOperationCompleted == null)) {
                this.setUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetUpdateOperationCompleted);
            }
            this.InvokeAsync("setUpdate", new object[] {
                        appName,
                        name,
                        param}, this.setUpdateOperationCompleted, userState);
        }
        
        private void OnsetUpdateOperationCompleted(object arg) {
            if ((this.setUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setUpdateCompleted(this, new setUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTableData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTableData(string appName, string name, string param) {
            object[] results = this.Invoke("getTableData", new object[] {
                        appName,
                        name,
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTableDataAsync(string appName, string name, string param) {
            this.getTableDataAsync(appName, name, param, null);
        }
        
        /// <remarks/>
        public void getTableDataAsync(string appName, string name, string param, object userState) {
            if ((this.getTableDataOperationCompleted == null)) {
                this.getTableDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTableDataOperationCompleted);
            }
            this.InvokeAsync("getTableData", new object[] {
                        appName,
                        name,
                        param}, this.getTableDataOperationCompleted, userState);
        }
        
        private void OngetTableDataOperationCompleted(object arg) {
            if ((this.getTableDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTableDataCompleted(this, new getTableDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void carreCompletedEventHandler(object sender, carreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class carreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal carreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void VerifyWbCompletedEventHandler(object sender, VerifyWbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyWbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyWbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getServerDateCompletedEventHandler(object sender, getServerDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getDataBaseDefinitionsCompletedEventHandler(object sender, getDataBaseDefinitionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataBaseDefinitionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataBaseDefinitionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void setUpdateCompletedEventHandler(object sender, setUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getTableDataCompletedEventHandler(object sender, getTableDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTableDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTableDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591